# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Compiling the Node.js code
  post_build:
    commands:
      - echo build process finished
# Include only the files required for your application to run.
# Do not use recursively include artifacts from node_modules directory as it will include unnecessary packages 
# used only for building and testing.
# ExpressJS apps will need other artifact directories included (bin/*, public/*, routes/*, views/* etc).
artifacts:
  files:
    - index.js
    - package.json
    - modules/*
    - node_modules/*
